version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    image: php:apache-pg
    environment:
      - POSTGRES_HOST=postgis
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=opendata
    volumes:
      - ./web:/var/www/html/
      - ./php-config:/usr/local/etc/php
      - ./apache-conf/apache2.conf:/etc/apache2/apache2.conf
      - ./apache-conf/reverse-proxy.conf:/etc/apache2/conf-enabled/reverse-proxy.conf
    ports:
      - 80:80
    restart: unless-stopped
  postgis:
    container_name: postgis
    hostname: postgis
    image: postgis/postgis
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=opendata
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/fcr_clean.csv:/docker-entrypoint-initdb.d/fcr_clean.csv
      - ./postgres-conf/postgres.conf:/etc/postgresql/postgresql.conf
      - ./data/large-files:/home/opendata
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  pgtileserv:
    container_name: pgtileserv
    hostname: pgtileserv
    image: pramsey/pg_tileserv:latest
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgis/opendata
      - TS_BASEPATH=/tiles
    ports:
      - 7800:7800
    restart: unless-stopped # container will fail if database is not ready to accept connections
  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=fred.morin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecretPassword
    ports:
      - 8001:80
    restart: unless-stopped
